In [15]:
import pandas as pd
import numpy as np
data = pd.Series(np.random.randn(9), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], [1,2,3,1,3,1,2,2,3]])
print(data)
print(data['b':'c'])
print(data[['b','d']])
#输出第二层index=2的值
print(data[:,2],'\n\n')
#unstack()函数重排数据为dataframe格式
data.unstack()
#stack()
data.unstack().stack()

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])
print(frame)
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state','color']
print(frame, '\n')
print(frame['Ohio'])

a  1    0.544144
   2   -0.718296
   3   -0.071388
b  1   -0.433476
   3   -0.525528
c  1    0.024383
   2    1.210941
d  2    0.015936
   3   -0.385261
dtype: float64
b  1   -0.433476
   3   -0.525528
c  1    0.024383
   2    1.210941
dtype: float64
b  1   -0.433476
   3   -0.525528
d  2    0.015936
   3   -0.385261
dtype: float64
a   -0.718296
c    1.210941
d    0.015936
dtype: float64


     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11
state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [25]:
print('########Reordering and Sorting Levels##########')
print(frame, '\n')
#swaplevel调换2个level的位置，但不影响数据值本身
print(frame.swaplevel('key1','key2'),'\n')
#sort_index可以根据单一的level来sort data
print(frame.sort_index(level=1),'\n')
print(frame.swaplevel(0,1), '\n')
print(frame.swaplevel(0,1).sort_index(level=0))

########Reordering and Sorting Levels##########
state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [28]:
print('########Summary Statistics by Level##########')
#针对不同的level进行数目统计, 输出table
print(frame.sum(level = 'key2'))
#对列特征color分类。列分类时候要设置axis = 1
print(frame.sum(level = 'color', axis = 1))

########Summary Statistics by Level##########
state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16
color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [32]:
print('########Indexing with a DataFrame’s columns##########')
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two', 'two',
                             'two', 'two'],
                      'd':[0,1,2,0,1,2,3]})
print(frame, '\n')
frame2 = frame.set_index(['c','d'])
print(frame.set_index(['c','d']), '\n')
print(frame.set_index(['c','d'], drop = False), '\n')
print(frame2.reset_index(), '\n')

########Indexing with a DataFrame’s columns##########
   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

#### 2 Combining and Merging Datasets

In [40]:
print('########Database-Style DataFrame Joins##########')
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})
print(df1, '\n', df2, '\n')
#merge函数，没写按哪个列merge，建议加上on= , 而且default为两个data相交（intersect）。
print(pd.merge(df1, df2, on = 'key'))

df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                     'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                     'data2': range(3)})
#如果key名字不一样，可以用left_on= 和right_on=来指定。
print(pd.merge(df3, df4, left_on='lkey', right_on='rkey'), '\n')

#两个data的数据都要用 how = 'outer', 只要第一个data的用'left'，要两个data同时有的用'inner'
print(pd.merge(df1, df2, how = 'outer'),'\n')

#多对多merge
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                    'data1': range(6)})
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
                    'data2': range(5)})
print(pd.merge(df1, df2, on='key', how='left'), '\n')

#根据多个keys来merge:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                      'key2': ['one', 'two', 'one'],
                      'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                       'key2': ['one', 'one', 'one', 'two'],
                       'rval': [4, 5, 6, 7]})
print(pd.merge(left, right, on=['key1', 'key2'], how='outer'))
print(pd.merge(left, right, on = 'key1'),'\n')
print(pd.merge(left, right, on='key1', suffixes=('_left', '_right')))

########Database-Style DataFrame Joins##########
  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
   key  data2
0   a      0
1   b      1
2   d      2

  key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0
  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

  key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

   key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

  key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0
  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [49]:
print('########Merging on Index##########')
import pandas as pd
import numpy as np
#可以用left_index=True和right_index=True 指示index作为merge key
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                       'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
print(pd.merge(left1, right1, left_on='key', right_index=True, how='outer'), '\n')

lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio','Nevada', 'Nevada'],
'key2': [2000, 2001, 2002, 2001, 2002],
'data': np.arange(5.)})
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),
                      index=[['Nevada', 'Nevada', 'Ohio', 'Ohio',
                              'Ohio', 'Ohio'],
                             [2001, 2000, 2000, 2000, 2001, 2002]],
                      columns=['event1', 'event2'])
print(pd.merge(lefth, righth, left_on=['key1','key2'], right_index=True),'\n')

#merge合并同时用两个data的index
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                      index=['a', 'c', 'e'],
                      columns=['Ohio', 'Nevada'])
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                       index=['b', 'c', 'd', 'e'],
                       columns=['Missouri', 'Alabama'])
print(pd.merge(left2, right2, left_index=True, right_index=True),'\n')

#join()函数可以根据index合并2个或多个data，index一样活着类似
print(left2.join(right2, how='outer'), '\n')


another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                        index=['a', 'c', 'e', 'f'],
                        columns=['New York', 'Oregon'])
print(left2.join([right2,another]), '\n')

########Merging on Index##########
  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

     key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1

   Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

   Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

/Users/theomarker/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:7277: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  res = concat(frames, axis=1, join="outer", verify_integrity=True)

In [68]:
print('########Concatenating Along an Axis##########')
arr = np.arange(12).reshape((3,4))
print(arr)
print(np.concatenate([arr,arr],axis=1),'\n')

#concat函数可以把多个series接起来
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
print(pd.concat([s1,s2,s3]), '\n')
#添加axis=1可以把series不合成一列，分列放
print(pd.concat([s1,s2,s3], axis=1),'\n')
#join_axes参数可以指定axes
s4 = pd.concat([s1, s3])
print(pd.concat([s1,s4],axis=1),'\n')
print(pd.concat([s1,s4],axis=1, join_axes=[['a','b','c','e']]),'\n')

#concat内的keys参数可以添加hierarchical index
result = pd.concat([s1,s2,s3], keys=['one','two','three'])
print(result, '\n\n')
print(result.unstack(), '\n')
#这里keys可以作为column header
print(pd.concat([s1,s2,s3], axis=1, keys=['one','two','three']),'\n')
#类似方法合并dataframe
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                    columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                    columns=['three', 'four'])
print(pd.concat([df1, df2], axis=1, keys=['level1','level2']), '\n')
print(pd.concat({'level1':df1, 'level2':df2},axis=1),'\n')
#用其他参数可以管理层次index
print(pd.concat([df1,df2], axis=1, keys=['level1','level2'], names=['upper','lower']), '\n')

#对于row index没有相关的data
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
print(pd.concat([df1, df2], ignore_index=True),'\n')

########Concatenating Along an Axis##########
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

     0    1
a  0.0  0.0
b  1.0  1.0
c  NaN  NaN
e  NaN  NaN

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64


         a    b    c    d    e    f    g
one    0.0  1.0  NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  2.0  3.0  4.0  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN  5.0  6.0

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

upper level1     level2
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

          a         b         c         d
0  0.614839 -0.977304  0.609431 -0.221497
1 -0.020237  1.305432  0.003138 -0.556779
2  0.110148 -1.544482  0.727953 -0.285119
3 -0.207973 -0.432453       NaN -1.370424
4 -1.119108 -1.646982       NaN -0.359447

/Users/theomarker/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if sys.path[0] == '':
/Users/theomarker/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  from ipykernel import kernelapp as app
/Users/theomarker/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  app.launch_new_instance()
/Users/theomarker/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/theomarker/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:29: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/theomarker/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:30: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/theomarker/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:32: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

/Users/theomarker/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:37: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [75]:
print('########Combining Data with Overlap##########')
#np的where函数，执行array-oriented的if-else:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
               index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),
               index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = np.nan
print(np.where(pd.isnull(a), b, a), '\n')
#combine_first可以做到同样的结果,如果data1没有，则括号里的data2补上
print(b[:-2])
print(a[2:])
print(b[:-2].combine_first(a[2:]))

df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                     'b': [np.nan, 2., np.nan, 6.],
                     'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
                     'b': [np.nan, 3., 4., 6., 8.]})
df1.combine_first(df2)

########Combining Data with Overlap##########
[0.  2.5 2.  3.5 4.5 nan]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

#### 3 Reshaping and Pivoting

In [79]:
print('########Reshaping with Hierarchical Indexing##########')
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                     index=pd.Index(['Ohio', 'Colorado'], name='state'),
                     columns=pd.Index(['one', 'two', 'three'],
                     name='number'))
print(data,'\n')
result = data.stack()
print(data.stack(), '\n')
#unstack(0)可以从另一个level来做
print(result.unstack(0),'\n')
print(result.unstack('state'),'\n')

df = pd.DataFrame({'left': result, 'right': result + 5},
                   columns=pd.Index(['left', 'right'], name='side'))
df.unstack('state')
df.unstack('state').stack('side')

########Reshaping with Hierarchical Indexing##########
number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [89]:
print('########Pivoting “Long” to “Wide” Format##########')
data = pd.read_csv('../examples/macrodata.csv')
data.head()
periods = pd.PeriodIndex(year=data.year, quarter=data.quarter, name='date')
columns = pd.Index(['realgdp', 'infl', 'unemp'], name='item')
data = data.reindex(columns=columns)
data.index = periods.to_timestamp('D','end')
print(data.head())
ldata = data.stack().reset_index().rename(columns={0:'value'})
print(ldata.head(),'\n')
pivoted = ldata.pivot('date', 'item', 'value')
print(pivoted.head(),'\n')

ldata['value2'] = np.random.randn(len(ldata))
pivoted = ldata.pivot('date','item')
print(pivoted.head())

########Pivoting “Long” to “Wide” Format##########
item                            realgdp  infl  unemp
date
1959-03-31 23:59:59.999999999  2710.349  0.00    5.8
1959-06-30 23:59:59.999999999  2778.801  2.34    5.1
1959-09-30 23:59:59.999999999  2775.488  2.74    5.3
1959-12-31 23:59:59.999999999  2785.204  0.27    5.6
1960-03-31 23:59:59.999999999  2847.699  2.31    5.2
                           date     item     value
0 1959-03-31 23:59:59.999999999  realgdp  2710.349
1 1959-03-31 23:59:59.999999999     infl     0.000
2 1959-03-31 23:59:59.999999999    unemp     5.800
3 1959-06-30 23:59:59.999999999  realgdp  2778.801
4 1959-06-30 23:59:59.999999999     infl     2.340

item                           infl   realgdp  unemp
date
1959-03-31 23:59:59.999999999  0.00  2710.349    5.8
1959-06-30 23:59:59.999999999  2.34  2778.801    5.1
1959-09-30 23:59:59.999999999  2.74  2775.488    5.3
1959-12-31 23:59:59.999999999  0.27  2785.204    5.6
1960-03-31 23:59:59.999999999  2.31  2847.699    5.2

                              value                    value2            \
item                           infl   realgdp unemp      infl   realgdp
date
1959-03-31 23:59:59.999999999  0.00  2710.349   5.8  0.946184  0.929775
1959-06-30 23:59:59.999999999  2.34  2778.801   5.1 -0.741368  0.193390
1959-09-30 23:59:59.999999999  2.74  2775.488   5.3  1.053869  1.705423
1959-12-31 23:59:59.999999999  0.27  2785.204   5.6 -0.759759  1.148088
1960-03-31 23:59:59.999999999  2.31  2847.699   5.2 -1.656499 -1.068588


item                              unemp
date
1959-03-31 23:59:59.999999999  0.769066
1959-06-30 23:59:59.999999999  0.917490
1959-09-30 23:59:59.999999999 -0.563104
1959-12-31 23:59:59.999999999 -0.666208
1960-03-31 23:59:59.999999999  0.349060

In [93]:
print('########Pivoting “Wide” to “Long” Format##########')
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
                    'A': [1, 2, 3],
                    'B': [4, 5, 6],
                    'C': [7, 8, 9]})
print(df, '\n')
melted = pd.melt(df, ['key'])
print(melted, '\n')
reshaped = melted.pivot('key','variable','value')
print(reshaped, '\n')
print(reshaped.reset_index(),'\n')
print(pd.melt(df, id_vars=['key'], value_vars=['A', 'B']))
pd.melt(df, value_vars=['A', 'B', 'C'])
pd.melt(df, value_vars=['key', 'A', 'B'])

########Pivoting “Wide” to “Long” Format##########
   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7